### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by lechatpito** [zazuko/xrm-csvw-workflow#22]
Hello,

I am getting the following error when running a pipeline. 

```
info: created new Pipeline {"iri":"http://example.org/pipeline/parseMetadata","timestamp":"2022-10-20T16:19:06.312Z"}
debug: initialize Pipeline {"iri":"http://example.org/pipeline/parseMetadata","timestamp":"2022-10-20T16:19:06.420Z"}
debug: created new StreamObject {"iri":"http://example.org/pipeline/readMetadataJson","timestamp":"2022-10-20T16:19:06.421Z"}
info: created new Step {"iri":"http://example.org/pipeline/readMetadataJson","timestamp":"2022-10-20T16:19:06.422Z"}
debug: created new StreamObject {"iri":"http://example.org/pipeline/parseMetadataJson","timestamp":"2022-10-20T16:19:06.427Z"}
info: created new Step {"iri":"http://example.org/pipeline/parseMetadataJson","timestamp":"2022-10-20T16:19:06.427Z"}
debug: initialized Pipeline {"iri":"http://example.org/pipeline/parseMetadata","timestamp":"2022-10-20T16:19:06.428Z"}
Error: error in forEach sub-pipeline http://example.org/pipeline/readMappingCsvTriples
    at ForEach._write (file:///home/runner/work/convertions-workflows-businees-graph/convertions-workflows-businees-graph/node_modules/barnard59-base/forEach.js:64:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Caused by: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Url.parse (node:url:168:3)
    at Object.urlParse [as parse] (node:url:155:13)
    at Function.fetch (/home/runner/work/convertions-workflows-businees-graph/convertions-workflows-businees-graph/node_modules/proto-fetch/index.js:4:24)
    at instance (/home/runner/work/convertions-workflows-businees-graph/convertions-workflows-businees-graph/node_modules/proto-fetch/index.js:15:18)
    at fetchData (file:///home/runner/work/convertions-workflows-businees-graph/convertions-workflows-businees-graph/node_modules/barnard59-csvw/lib/fetchData.js:5:21)
    at file:///home/runner/work/convertions-workflows-businees-graph/convertions-workflows-businees-graph/node_modules/barnard59-csvw/fetch.js:18:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Process completed with exit code 1.
```

Any idea what's going on?

**Comment by ktk** [comment]
Looks like it can't find the location of the CSV file, which it gets from reading the CSVW metadata file. Can you share the part of the json-file that contains the location?

**Comment by lechatpito** [comment]
So this error happens when I have more than one logical source in use in the mapping. 
I can declare as many sources as wanted, but if I have more than one map I get the aforementioned error. For your reference I am using a source group. I do not see anything wrong with the generated .csv.meta.json 
Not sharing the actual code yet as it would require redacting data but I can if necessary

**Comment by ktk** [comment]
Sorry I lost track of this issue.

So you had more than one mapping in the same file, this is not supported by our CSVW processor at the moment. The workaround here is to simply put every mapping in a separate file. XRM will then create multiple output files and CSVW will happily process them one by one.

**Comment by lechatpito** [comment]
Sounds good, thanks for the follow up
